version: "3.8"
services:
    translation-server:
        image: parkernilson/ende-server
        build: ./server
        environment:
            ENV: production
            FLASK_APP: /code/server.py
            FLASK_ENV: production
        volumes:
            - ~/ml_models/ende/1:/models/ende/1
        ports:
            - 5000:5000
        restart: unless-stopped
    client-files:
        image: parkernilson/ende-client
        build: ./client
        volumes:
            - client-files:/public
    reverse-proxy:
        image: parkernilson/ende-reverse-proxy
        build: ./reverse-proxy
        ports: 
            - 80:80
            - 9000:9000
        volumes: 
            - client-files:/usr/share/nginx/html
        depends_on:
            - translation-server
            - client-files
        links:
            - translation-server
        restart: unless-stopped

volumes:
    client-files: