version: "3.8"
services:
    translation-server:
        image: parkernilson/ende-server
        build: ./server
        environment:
            ENV: production
            FLASK_APP: /code/server.py
            FLASK_ENV: production
        volumes:
            - ~/ml_models/ende/1:/models/ende/1
        ports:
            - 5000:5000
    client:
        image: parkernilson/ende-client
        build: ./client
        ports:
            - 5001:80
        depends_on: 
            - translation-server
        links: 
            - translation-server